### ISSUE TITLE
Heartbeat crash

### ISSUE THREAD

**Issue by nairaner** [eddy5641/LegendaryClient#101]
Heartbeat is sent twice maybe??

```
(11/5/2014 10:28 AM) [LOG]: LegendaryClient Has Finished Patching
(11/5/2014 10:28 AM) [LOG]: LegendaryClient Started Up Successfully
(11/5/2014 10:28 AM) [LOG]: Starting Patcher
(11/5/2014 10:28 AM) [EXCEPTION]: A first chance exception was thrown
(11/5/2014 10:28 AM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(11/5/2014 10:28 AM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(11/5/2014 10:28 AM) [LOG]: DataDragon Version: 4.18.1
(11/5/2014 10:28 AM) [LOG]: Current DataDragon Version: 4.18.1
(11/5/2014 10:28 AM) [LOG]: DDragon Version (LOL Version) = 4.18.1
(11/5/2014 10:28 AM) [LOG]: Client Version: 4.18.1
(11/5/2014 10:28 AM) [LOG]: Air Assets Version: 0.0.1.115
(11/5/2014 10:28 AM) [LOG]: Current Air Assets Version: 0.0.1.116
(11/5/2014 10:28 AM) [LOG]: Trying to detect League of Legends GameClient
(11/5/2014 10:28 AM) [LOG]: League of Legends is located at: C:/Riot Games/League of Legends
(11/5/2014 10:28 AM) [LOG]: Latest League of Legends GameClient: 0.0.1.63
(11/5/2014 10:28 AM) [LOG]: Checking if League of Legends is Up-To-Date
(11/5/2014 10:28 AM) [LOG]: League of Legends is Up-To-Date
(11/5/2014 10:28 AM) [LOG]: LegendaryClient Has Finished Patching
(11/5/2014 10:29 AM) [EXCEPTION]: A first chance exception was thrown
(11/5/2014 10:29 AM) [EXCEPTION]: An invalid IP address was specified.
(11/5/2014 10:29 AM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(11/5/2014 10:29 AM) [LOG]: Connected and logged in as Nairaner
(11/5/2014 10:29 AM) [EXCEPTION]: A first chance exception was thrown
(11/5/2014 10:29 AM) [EXCEPTION]: Application identity is not set.
(11/5/2014 10:29 AM) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(11/5/2014 10:30 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:30 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:32 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:32 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_BulletTime.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_DoubleUp.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_ImpureShots.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_MakeItRain.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_Strut.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_BulletTime.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_DoubleUp.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_ImpureShots.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_MakeItRain.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_Strut.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_BulletTime.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_DoubleUp.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_ImpureShots.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_MakeItRain.png
(11/5/2014 10:34 AM) [WARN]: Cannot find C:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\bin\Debug\Assets\abilities\MissFortune_Strut.png
(11/5/2014 10:34 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:34 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:36 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:36 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:38 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:38 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:41 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:41 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:43 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 10:43 AM) [EXCEPTION]: A first chance exception was thrown
(11/5/2014 10:43 AM) [EXCEPTION]: The Write method cannot be called when another write operation is pending.
(11/5/2014 10:43 AM) [EXCEPTION]:    at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
(11/5/2014 10:43 AM) [EXCEPTION]: A first chance exception was thrown
(11/5/2014 10:43 AM) [EXCEPTION]: The Write method cannot be called when another write operation is pending.
(11/5/2014 10:43 AM) [EXCEPTION]:    at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:line 764
   at PVPNetConnect.PVPNetConnection.Invoke(String destination, Object operation, Object body) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:line 780
   at PVPNetConnect.PVPNetConnection.<PerformLCDSHeartBeat>d__29.MoveNext() in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PublicMethods.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
(11/5/2014 11:08 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 11:08 AM) [LOG]: Preforming LCDSHeartBeat
(11/5/2014 11:08 AM) [EXCEPTION]: A first chance exception was thrown
(11/5/2014 11:08 AM) [EXCEPTION]: The Write method cannot be called when another write operation is pending.
(11/5/2014 11:08 AM) [EXCEPTION]:    at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:line 764
   at PVPNetConnect.PVPNetConnection.Invoke(String destination, Object operation, Object body) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:line 780
   at PVPNetConnect.PVPNetConnection.<PerformLCDSHeartBeat>d__29.MoveNext() in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PublicMethods.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LegendaryClient.Logic.Client.<DoHeartbeat>d__7.MoveNext() in c:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\Logic\Client.cs:line 711
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
(11/5/2014 11:08 AM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(11/5/2014 11:08 AM) [UNHANDLEDEXCEPTION]: The Write method cannot be called when another write operation is pending.
(11/5/2014 11:08 AM) [UNHANDLEDEXCEPTION]:    at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:line 764
   at PVPNetConnect.PVPNetConnection.Invoke(String destination, Object operation, Object body) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:line 780
   at PVPNetConnect.PVPNetConnection.<PerformLCDSHeartBeat>d__29.MoveNext() in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\PublicMethods.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LegendaryClient.Logic.Client.<DoHeartbeat>d__7.MoveNext() in c:\Users\Krzysztof\Source\Repos\LegendaryClient\LegendaryClient\Logic\Client.cs:line 711
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by Dispersia** [comment]
Is this the only time it did this?

**Comment by nairaner** [comment]
it happened to me like 3 times, but i noticed that heartbeat is called in mainwindow and in loginpage, so i guess it just overlaps

**Comment by eddy5641** [comment]
I will fix this

**Comment by eddy5641** [comment]
Should be fixed. Compile LC
