### ISSUE TITLE
Crash as soon as it's done patching 

### ISSUE THREAD

**Issue by ghost** [eddy5641/LegendaryClient#130]
First of all, I am a noobie at github and I am still around beginner level on C#. I like to view projects and learn from them etc.

Worked fine the first time. But when I started the client once again, it crashes as soon as it prints out "League of Legends is Up-To-Date"...

(2014-12-06 17:51) [LOG]: LegendaryClient Has Finished Patching
(2014-12-06 17:51) [LOG]: LegendaryClient Started Up Successfully
(2014-12-06 17:51) [LOG]: Starting Patcher
(2014-12-06 17:51) [LOG]: DataDragon Version: 4.20.1
(2014-12-06 17:51) [LOG]: Current DataDragon Version: 4.20.1
(2014-12-06 17:51) [LOG]: DDragon Version (LOL Version) = 4.20.1
(2014-12-06 17:51) [LOG]: Client Version: 4.20.1
(2014-12-06 17:51) [LOG]: Air Assets Version: 0.0.1.119
(2014-12-06 17:51) [LOG]: Current Air Assets Version: 0.0.1.119
(2014-12-06 17:51) [LOG]: Trying to detect League of Legends GameClient
(2014-12-06 17:51) [LOG]: League of Legends is located at: C:\Program Files (x86)\Riot\League of Legends\
(2014-12-06 17:51) [LOG]: Latest League of Legends GameClient: 0.0.1.68
(2014-12-06 17:51) [LOG]: Checking if League of Legends is Up-To-Date
(2014-12-06 17:51) [LOG]: League of Legends is Up-To-Date
(2014-12-06 17:51) [LOG]: LegendaryClient Has Finished Patching
(2014-12-06 17:51) [EXCEPTION]: A first chance exception was thrown
(2014-12-06 17:51) [EXCEPTION]: Value cannot be null.
Parameter name: path4
(2014-12-06 17:51) [EXCEPTION]:    at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
(2014-12-06 17:51) [EXCEPTION]: A first chance exception was thrown
(2014-12-06 17:51) [EXCEPTION]: Exception has been thrown by the target of an invocation.
(2014-12-06 17:51) [EXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
(2014-12-06 17:51) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2014-12-06 17:51) [UNHANDLEDEXCEPTION]: Exception has been thrown by the target of an invocation.
(2014-12-06 17:51) [UNHANDLEDEXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at LegendaryClient.App.Main() in c:\Users\DeniCevap\Documents\GitHub\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0

**Comment by nairaner** [comment]
Try pulling now, I reverted some bad changes

**Comment by ghost** [comment]
Works perfectly now, thanks!

**Comment by RoachxD** [comment]
I'm an idiot, I pushed the wrong patch..
I will push the other as fast as I finish the game..
