### ISSUE TITLE
Spectate Games

### ISSUE THREAD

**Issue by drkcodeman** [eddy5641/LegendaryClient#142]
Unable to spectate games.

**Comment by Dispersia** [comment]
a little more detail please, what happens exactly? what server? Would you be able to post a log, maybe there was a connection issue, does the LoL client crash or?

 with 4.21 they may have changed someones spectate url (they have been doing that a lot recently)

**Comment by drkcodeman** [comment]
As soon as you attempt to spectate a game off friends list the client crashes.  I will post from the log file here shortly.

**Comment by drkcodeman** [comment]
(12/10/2014 6:48 PM) [EXCEPTION]: A first chance exception was thrown
(12/10/2014 6:48 PM) [EXCEPTION]: Object reference not set to an instance of an object.
(12/10/2014 6:48 PM) [EXCEPTION]:    at LegendaryClient.Windows.FriendList.<SpectateGame_Click>d__3.MoveNext()
(12/10/2014 6:48 PM) [EXCEPTION]: A first chance exception was thrown
(12/10/2014 6:48 PM) [EXCEPTION]: Object reference not set to an instance of an object.
(12/10/2014 6:48 PM) [EXCEPTION]:    at LegendaryClient.Windows.FriendList.<SpectateGame_Click>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
(12/10/2014 6:48 PM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(12/10/2014 6:48 PM) [UNHANDLEDEXCEPTION]: Object reference not set to an instance of an object.
(12/10/2014 6:48 PM) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Windows.FriendList.<SpectateGame_Click>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

**Comment by drkcodeman** [comment]
I am on 32 bit

**Comment by Dispersia** [comment]
ah, I can reproduce. I will fix it very soon, thank you for the report! (must be something to do with the new groups, I'm so happy he implemented those lol.)

**Comment by Dispersia** [comment]
Fixed.
