### ISSUE TITLE
View profile friends in friend list crash client

### ISSUE THREAD

**Issue by matheuszig** [eddy5641/LegendaryClient#145]
Crash client after click in View Profile on friendlist 
log:
(11/12/2014 00:50) [LOG]: LegendaryClient Started Up Successfully
(11/12/2014 00:50) [LOG]: Starting Patcher
(11/12/2014 00:50) [LOG]: DataDragon Version: 4.21.5
(11/12/2014 00:50) [LOG]: Current DataDragon Version: 4.21.5
(11/12/2014 00:50) [LOG]: DDragon Version (LOL Version) = 4.21.5
(11/12/2014 00:50) [LOG]: Client Version: 4.21.5
(11/12/2014 00:50) [LOG]: Air Assets Version: 0.0.1.120
(11/12/2014 00:50) [LOG]: Current Air Assets Version: 0.0.1.120
(11/12/2014 00:50) [LOG]: Trying to detect League of Legends GameClient
(11/12/2014 00:50) [LOG]: League of Legends is located at: E:\Riot Games\League of Legends\
(11/12/2014 00:50) [LOG]: Latest League of Legends GameClient: 0.0.1.69
(11/12/2014 00:50) [LOG]: Checking if League of Legends is Up-To-Date
(11/12/2014 00:50) [LOG]: League of Legends is Up-To-Date
(11/12/2014 00:50) [LOG]: LegendaryClient Has Finished Patching
(11/12/2014 00:51) [EXCEPTION]: A first chance exception was thrown
(11/12/2014 00:51) [EXCEPTION]: An invalid IP address was specified.
(11/12/2014 00:51) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(11/12/2014 00:51) [LOG]: Connected to BR and logged in as Ratinhuu
(11/12/2014 00:51) [EXCEPTION]: A first chance exception was thrown
(11/12/2014 00:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(11/12/2014 00:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(11/12/2014 00:51) [EXCEPTION]: A first chance exception was thrown
(11/12/2014 00:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(11/12/2014 00:51) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(11/12/2014 00:51) [EXCEPTION]: A first chance exception was thrown
(11/12/2014 00:51) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(11/12/2014 00:51) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(11/12/2014 00:51) [EXCEPTION]: A first chance exception was thrown
(11/12/2014 00:51) [EXCEPTION]: Object reference not set to an instance of an object.
(11/12/2014 00:51) [EXCEPTION]:    at LegendaryClient.Windows.FriendList.ProfileItem_Click(Object sender, RoutedEventArgs e)
(11/12/2014 00:51) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(11/12/2014 00:51) [UNHANDLEDEXCEPTION]: Object reference not set to an instance of an object.
(11/12/2014 00:51) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Windows.FriendList.ProfileItem_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

**Comment by Dispersia** [comment]
download the latest version of 2.2.0.1, this should be fixed
