### ISSUE TITLE
Crash instantly upon login

### ISSUE THREAD

**Issue by Avunit** [eddy5641/LegendaryClient#156]
Below is my relevant log file:

(14/12/2014 08:59) [LOG]: LegendaryClient Has Finished Patching
(14/12/2014 08:59) [LOG]: LegendaryClient Started Up Successfully
(14/12/2014 08:59) [LOG]: Starting Patcher
(14/12/2014 08:59) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 08:59) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(14/12/2014 08:59) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(14/12/2014 08:59) [LOG]: DataDragon Version: 4.21.5
(14/12/2014 08:59) [LOG]: Current DataDragon Version: 4.21.5
(14/12/2014 08:59) [LOG]: DDragon Version (LOL Version) = 4.21.5
(14/12/2014 08:59) [LOG]: Client Version: 4.21.5
(14/12/2014 08:59) [LOG]: Air Assets Version: 0.0.1.121
(14/12/2014 08:59) [LOG]: Current Air Assets Version: 0.0.1.121
(14/12/2014 08:59) [LOG]: Trying to detect League of Legends GameClient
(14/12/2014 08:59) [LOG]: League of Legends is located at: D:\Games\Riot Games\League of Legends\
(14/12/2014 08:59) [LOG]: Latest League of Legends GameClient: 0.0.1.70
(14/12/2014 08:59) [LOG]: Checking if League of Legends is Up-To-Date
(14/12/2014 08:59) [LOG]: League of Legends is Up-To-Date
(14/12/2014 08:59) [LOG]: LegendaryClient Has Finished Patching
(14/12/2014 09:01) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 09:01) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(14/12/2014 09:01) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(14/12/2014 09:01) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 09:01) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(14/12/2014 09:01) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(14/12/2014 09:01) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 09:01) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(14/12/2014 09:01) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(14/12/2014 09:01) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 09:01) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(14/12/2014 09:01) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(14/12/2014 09:01) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 09:01) [EXCEPTION]: An invalid IP address was specified.
(14/12/2014 09:01) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(14/12/2014 09:01) [LOG]: Connected and logged in as2tegleajvara
(14/12/2014 09:01) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 09:01) [EXCEPTION]: Application identity is not set.
(14/12/2014 09:01) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(14/12/2014 09:01) [EXCEPTION]: A first chance exception was thrown
(14/12/2014 09:01) [EXCEPTION]: Object reference not set to an instance of an object.
(14/12/2014 09:01) [EXCEPTION]:    at LegendaryClient.Windows.MainPage.ParseSpectatorGames() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 379
(14/12/2014 09:01) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(14/12/2014 09:01) [UNHANDLEDEXCEPTION]: Object reference not set to an instance of an object.
(14/12/2014 09:01) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Windows.MainPage.ParseSpectatorGames() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 379
   at LegendaryClient.Windows.MainPage.<ChangeSpectatorRegion>b__e(Object s, RunWorkerCompletedEventArgs args) in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\MainPage.xaml.cs:line 274
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:line 0

**Comment by nairaner** [comment]
Try downloading the latest client
