### ISSUE TITLE
Next Spectate 

### ISSUE THREAD

**Issue by Lolr** [eddy5641/LegendaryClient#85]
On clicking the next button for the spectating games it crashes, here's the log

(27/10/2014 21:49) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 21:49) [LOG]: LegendaryClient Started Up Successfully
(27/10/2014 21:49) [LOG]: Starting Patcher
(27/10/2014 21:49) [LOG]: DataDragon Version: 4.18.1
(27/10/2014 21:49) [LOG]: Current DataDragon Version: 4.18.1
(27/10/2014 21:49) [LOG]: DDragon Version (LOL Version) = 4.18.1
(27/10/2014 21:49) [LOG]: Client Version: 4.18.1
(27/10/2014 21:49) [LOG]: Air Assets Version: 0.0.1.115
(27/10/2014 21:49) [LOG]: Current Air Assets Version: 0.0.1.115
(27/10/2014 21:49) [LOG]: Trying to detect League of Legends GameClient
(27/10/2014 21:49) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(27/10/2014 21:49) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(27/10/2014 21:49) [LOG]: Checking if League of Legends is Up-To-Date
(27/10/2014 21:49) [LOG]: League of Legends is Up-To-Date
(27/10/2014 21:49) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 21:49) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 21:49) [EXCEPTION]: no such table: champions
(27/10/2014 21:49) [EXCEPTION]:    at SQLite.SQLite3.Prepare2(IntPtr db, String query)
(27/10/2014 21:49) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(27/10/2014 21:49) [UNHANDLEDEXCEPTION]: no such table: champions
(27/10/2014 21:49) [UNHANDLEDEXCEPTION]:    at SQLite.SQLite3.Prepare2(IntPtr db, String query)
   at SQLite.SQLiteCommand.Prepare()
   at SQLite.SQLiteCommand.<ExecuteDeferredQuery>d__0`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SQLite.SQLiteCommand.ExecuteQuery[T]()
   at SQLite.TableQuery`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LegendaryClient.Windows.LoginPage..ctor()
   at LegendaryClient.Windows.PatcherPage.SkipPatchButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

Upon further investigation seems to only be a problem on the servers where there are no spectating sessions to be found.

**Comment by juaoose** [comment]
This does not make my client crash.

Only when selecting RU it will freeze.

**Comment by nairaner** [comment]
I think this log is caused by missing gamestats

**Comment by eddy5641** [comment]
Gamestats file is corrupted. Please replace this file
This can also be the bug where it has trouble reading the stats. If it is consistent, replace the Gamestats file

**Comment by Dispersia** [comment]
Doesn't download bad gamestats anymore.
