### ISSUE TITLE
Custom Start Game

### ISSUE THREAD

**Issue by Lolr** [eddy5641/LegendaryClient#88]
Here's the error I get for that

(27/10/2014 23:51) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:51) [LOG]: LegendaryClient Started Up Successfully
(27/10/2014 23:51) [LOG]: Starting Patcher
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(27/10/2014 23:51) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(27/10/2014 23:51) [LOG]: DataDragon Version: 4.18.1
(27/10/2014 23:51) [LOG]: Current DataDragon Version: 4.18.1
(27/10/2014 23:51) [LOG]: DDragon Version (LOL Version) = 4.18.1
(27/10/2014 23:51) [LOG]: Client Version: 4.18.1
(27/10/2014 23:51) [LOG]: Air Assets Version: 0.0.1.115
(27/10/2014 23:51) [LOG]: Current Air Assets Version: 0.0.1.115
(27/10/2014 23:51) [LOG]: Trying to detect League of Legends GameClient
(27/10/2014 23:51) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(27/10/2014 23:51) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(27/10/2014 23:51) [LOG]: Checking if League of Legends is Up-To-Date
(27/10/2014 23:51) [LOG]: League of Legends is Up-To-Date
(27/10/2014 23:51) [LOG]: LegendaryClient Has Finished Patching
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: An invalid IP address was specified.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(27/10/2014 23:51) [LOG]: Connected and logged in asMrBelgio
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(27/10/2014 23:51) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(27/10/2014 23:51) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:51) [EXCEPTION]: Application identity is not set.
(27/10/2014 23:51) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateGameConfig()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateSpectatorCode()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateGameConfig()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateSpectatorCode()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateGameConfig()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateSpectatorCode()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateGameConfig()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.CreateCustomGamePage.GenerateSpectatorCode()
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Object reference not set to an instance of an object.
(27/10/2014 23:52) [EXCEPTION]:    at LegendaryClient.Windows.ChampSelectPage.<StartChampSelect>b__0(ChampionDTO x, ChampionDTO y)
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:52) [EXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
(27/10/2014 23:52) [EXCEPTION]: A first chance exception was thrown
(27/10/2014 23:52) [EXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:52) [EXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at LegendaryClient.Windows.ChampSelectPage.<StartChampSelect>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
(27/10/2014 23:52) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(27/10/2014 23:52) [UNHANDLEDEXCEPTION]: Failed to compare two elements in the array.
(27/10/2014 23:52) [UNHANDLEDEXCEPTION]:    at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at LegendaryClient.Windows.ChampSelectPage.<StartChampSelect>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

**Comment by eddy5641** [comment]
I will check this out for you

**Comment by nairaner** [comment]
Champ select was change a lot, should be fixed now
