### ISSUE TITLE
Joining team chat

### ISSUE THREAD

**Issue by nairaner** [eddy5641/LegendaryClient#96]
Joining team queue chat makes you unable to be invited again http://puu.sh/cCMk2/a57b572a96.jpg

``` Log
(11/4/2014 10:38 AM) [LOG]: LegendaryClient Has Finished Patching
(11/4/2014 10:38 AM) [LOG]: LegendaryClient Started Up Successfully
(11/4/2014 10:38 AM) [LOG]: Starting Patcher
(11/4/2014 10:38 AM) [EXCEPTION]: A first chance exception was thrown
(11/4/2014 10:38 AM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(11/4/2014 10:38 AM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(11/4/2014 10:38 AM) [LOG]: DataDragon Version: 4.18.1
(11/4/2014 10:38 AM) [LOG]: Current DataDragon Version: 4.18.1
(11/4/2014 10:38 AM) [LOG]: DDragon Version (LOL Version) = 4.18.1
(11/4/2014 10:38 AM) [LOG]: Client Version: 4.18.1
(11/4/2014 10:38 AM) [LOG]: Air Assets Version: 0.0.1.115
(11/4/2014 10:38 AM) [LOG]: Current Air Assets Version: 0.0.1.115
(11/4/2014 10:38 AM) [LOG]: Trying to detect League of Legends GameClient
(11/4/2014 10:38 AM) [LOG]: League of Legends is located at: C:/Riot Games/League of Legends
(11/4/2014 10:38 AM) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(11/4/2014 10:38 AM) [LOG]: Checking if League of Legends is Up-To-Date
(11/4/2014 10:38 AM) [LOG]: League of Legends is Up-To-Date
(11/4/2014 10:38 AM) [LOG]: LegendaryClient Has Finished Patching
(11/4/2014 10:38 AM) [EXCEPTION]: A first chance exception was thrown
(11/4/2014 10:38 AM) [EXCEPTION]: An invalid IP address was specified.
(11/4/2014 10:38 AM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(11/4/2014 10:38 AM) [LOG]: Connected and logged in asNairaner
(11/4/2014 10:38 AM) [EXCEPTION]: A first chance exception was thrown
(11/4/2014 10:38 AM) [EXCEPTION]: Application identity is not set.
(11/4/2014 10:38 AM) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(11/4/2014 10:39 AM) [EXCEPTION]: A first chance exception was thrown
(11/4/2014 10:39 AM) [EXCEPTION]: Unable to cast object of type 'PVPNetConnect.TypedObject' to type 'System.Object[]'.
(11/4/2014 10:39 AM) [EXCEPTION]:    at PVPNetConnect.TypedObject.GetArray(String key) in c:\Users\Krzysztof\Source\Repos\LegendaryClient\PVPNetConnect\TypedObject.cs:line 84
(11/4/2014 10:39 AM) [EXCEPTION]: A first chance exception was thrown
(11/4/2014 10:39 AM) [EXCEPTION]: The given key was not present in the dictionary.
(11/4/2014 10:39 AM) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(11/4/2014 10:39 AM) [EXCEPTION]: A first chance exception was thrown
(11/4/2014 10:39 AM) [EXCEPTION]: The given key was not present in the dictionary.
(11/4/2014 10:39 AM) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(11/4/2014 10:40 AM) [LOG]: Preforming LCDSHeartBeat
```

**Comment by Dispersia** [comment]
Alright so the Join from jabber-net resets your presence. That's fine, so I was going to just call OnJoin to refresh your precence. Just found out, Join never finishes. it goes in and never comes out(at least OnJoin never gets fired). I just commit'd a temporary (dirty) fix. Close this if it works, should work for all pages now that I think about it.

**Comment by nairaner** [comment]
It works, but still can notice the problem for split second

**Comment by Dispersia** [comment]
Ya, it should flick. It sets the presence to "" then instantly fixes it. I don't know of a fix without fixing jabber-net as I don't know why it's changing the presence in the first place to nothing and why OnJoin isn't firing, but hey (I will hate jabber-net until I die). Closing because issue is fixed, added to TODO to fix jabber-net/replace it.
